language: ruby
rvm:
  - 2.2.2
  - 2.1.0
  - 2.0.0
  - ruby-head
  - jruby
  - rbx

env:
  - MONGOID_VERSION=3
  - MONGOID_VERSION=4
  - MONGOID_VERSION=5
  - MONGOID_VERSION=6

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-19mode
    - rvm: rbx
    - rvm: rbx-19mode

services: mongodb
